Final project
vic778/Space-Travelers-Hub pull request #45
Opened 2022-02-04 09:03 UTC by vic778

in this final part I have created :
- profile page that contains all reservations and all mission desc,
- mission page that contains all missions  took in the mission component 
- rock pages that contain all felons then the user can reserve as well 
- header component that contains all links and that navigate the user to the page clicked on 
- mission component  that contains all items get from the API and fetching with redux to reserve or cancel the reservation 
- rockets component contains all falcons available in the server(Database) the user can reserve or not.
- assets that contain all my styles using styled-components.
- app.js contains all routes 
- inde.js contain my provider and store.

2022-02-04 11:26 UTC, oloomoses requested changes
Hi team 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._
- [ ] Kindly add unit test for the project.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_Slack: Oloo Moses_
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-04 12:18 UTC, vic778 commented
## My partner was detached by Microverse, so I am working alone on this project, which is why my Readme contains only one author.

2022-02-04 13:01 UTC, oloomoses commented
> ## My partner was detached by Microverse, so I am working alone on this project, which is why my Readme contains only one author.

## Understood. One more thing I forgot. Kindly remember to add unit tests for the project.

2022-02-04 14:51 UTC, Meltrust requested changes
Hi @vic778, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-04 14:51 UTC, Meltrust commented on src/components/Header.js
> +      </nav>
- [ ] As the previous reviewer requested, the active link of the navbar should be underlined.  In other words, the currently active page should be indicated with an underline.

That way, we increase the user experience! 💪

2022-02-04 14:51 UTC, Meltrust commented on src/components/MissionItem.js
> +/* eslint-disable react/prop-types */
- [ ] As the last reviewer requested, kindly please enable the eslint rule and fix the issue.  

TIP: 

You have a typo calling `prototypes` on line 48 and that is why your validation does not work.  It should be `MissionItem.propTypes`.  Now, please delete that eslint-disable line.👍

2022-02-04 14:51 UTC, Meltrust commented on src/redux/Rockets/Rockets.js
> +};
- [ ] As the other reviewer said, please don't deactivate this rule and instead fix it.

TIP:

On line 30, you could just do `throw new Error('Something went wrong');` instead of the `return error` that you have.  That solves the problem.  Now, please  delete that eslint-disable.

2022-02-04 14:51 UTC, Meltrust commented on src/redux/Missions/Missions.js
> +};
- [ ] Please, kindly dispatch `fetchMission` inside the `fetchMissionsApi ` function as the last reviewer requested.

2022-02-04 14:51 UTC, Meltrust commented on src/components/Rocket.js
> +  const dispatch = useDispatch();
- [ ] As the previous reviewer requested, please kindly make use of `useSelector` instead of passing props.

2022-02-04 18:33 UTC, Gambit142 requested changes
Hi @vic778 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
- Your project is not loading on my end, I guess you have added extra `dependencies/loaders` that can't work outside of the `src` folder. Kindly fix it
- You don't have `Stylelint` in your `.github/workflows/linters.yml` file. Kindly configure it so that `Stylelint` can run checks on Github.

#### _Kindly check the comments under the review._

### The next reviewer should kindly check if all suggestions made by the previous reviewer were carried out as I could not verify because the _**author**_ deleted some files that changes were suggested on and his project did not start on my local machine. 🙏 😄 👍 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-04 18:33 UTC, Gambit142 commented on .github/workflows/linters.yml
> +        run: npx eslint .
- [ ] Kindly add `Stylelint` back to this file. You should not touch the linters file except the project requirements tells you to do so. Please add the configuration back and ensure it passes. 👍 You could use this:

```
 stylelint:
    name: Stylelint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup Stylelint
        run: |
          npm install --save-dev stylelint@13.x stylelint-scss@3.x stylelint-config-standard@21.x stylelint-csstree-validator@1.x
          [ -f .stylelintrc.json ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/react-redux/.stylelintrc.json
      - name: Stylelint Report
        run: npx stylelint "**/*.{css,scss}"
```

2022-02-04 18:33 UTC, Gambit142 commented on src/redux/modules/camelConverter.js
> +};
- [ ] You do not need this file nor the `modules` folder to make calls to the `API`. Kindly delete it as I strongly suspect that it is the reason why your project is broken and I can't start your project on my local machine. 🙏

2022-02-04 18:33 UTC, Gambit142 commented on src/redux/missions/missions.js
> +  const payload = Camel.keysToCamel(response.data).map((e) => {
- [ ] You don't need **_line 13_** to make `Axios` calls. You can use the following lines of code to fetch data from the mission endpoint provided for this project:

```
 axios
        .get('https://api.spacexdata.com/v3/missions')
        .then((missions) => yourFunction(missions.data, dispatch));
```

Kindly implement this change. 👍

2022-02-04 19:21 UTC, vic778 commented on src/redux/missions/missions.js
> +  const payload = Camel.keysToCamel(response.data).map((e) => {
https://space-travel-book.netlify.app/ can u please try this one

2022-02-04 20:44 UTC, rukundoeric approved these changes
Hi @vic778,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_


Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

------
>As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-04 20:52 UTC, merged

2022-02-05 00:02 UTC, mke2111 reviewed
Hello @vic778 👋,

_This is an additional review as a result of the second opinion request._

I'm glad that the issue here has been resolved and your project is already approved. 



Keep rocking 🚀 & Happy Coding 💻